name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository source code
        uses: actions/checkout@v4
      - name: Setting up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start deployment to Production
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
